C------------------------------------------------------------------------------
C Version 25-November-1996                                     File: futils.inc
C------------------------------------------------------------------------------
C Copyright N. Cardiel & J. Gorgas, Departamento de Astrofisica
C Universidad Complutense de Madrid, 28040-Madrid, Spain
C E-mail: ncl@astrax.fis.ucm.es or fjg@astrax.fis.ucm.es
C------------------------------------------------------------------------------
C This file is free software; you can redistribute it and/or modify it
C under the terms of the GNU General Public License as published by the Free
C Software Foundation; either version 2 of the License, or (at your option) any
C later version. See the file gnu-public-license.txt for details.
C------------------------------------------------------------------------------
        CHARACTER*255   READC               !read character
!       INTEGER         READI               !read integer
!       INTEGER         READILIM            !read integer inside a range
!       REAL            READF               !read float
!       INTEGER         TRUEBEG,TRUELEN     !character manipulation
C------------------------------------------------------------------------------
